// Code generated by goyacc -v y.output grammar.y. DO NOT EDIT.

//line grammar.y:6

package parser

import __yyfmt__ "fmt"

//line grammar.y:7

// Grammar for Python

import (
	"fmt"
	"github.com/go-python/gpython/ast"
	"github.com/go-python/gpython/py"
)

// NB can put code blocks in not just at the end

// Returns a Tuple if > 1 items or a trailing comma, otherwise returns
// the first item in elts
func tupleOrExpr(pos ast.Pos, elts []ast.Expr, optional_comma bool) ast.Expr {
	if optional_comma || len(elts) > 1 {
		return &ast.Tuple{ExprBase: ast.ExprBase{Pos: pos}, Elts: elts, Ctx: ast.Load}
	} else {
		return elts[0]
	}
}

// Apply trailers (if any) to expr
//
// trailers are half made Call, Subscript or Attribute
func applyTrailers(expr ast.Expr, trailers []ast.Expr) ast.Expr {
	//trailers := $1
	for _, trailer := range trailers {
		switch x := trailer.(type) {
		case *ast.Call:
			x.Func, expr = expr, x
		case *ast.Subscript:
			x.Value, expr = expr, x
		case *ast.Attribute:
			x.Value, expr = expr, x
		default:
			panic(fmt.Sprintf("Unknown trailer type: %T", expr))
		}
	}
	return expr
}

// Set the context for expr
func setCtx(yylex yyLexer, expr ast.Expr, ctx ast.ExprContext) {
	setctxer, ok := expr.(ast.SetCtxer)
	if !ok {
		expr_name := ""
		switch expr.(type) {
		case *ast.Lambda:
			expr_name = "lambda"
		case *ast.Call:
			expr_name = "function call"
		case *ast.BoolOp, *ast.BinOp, *ast.UnaryOp:
			expr_name = "operator"
		case *ast.GeneratorExp:
			expr_name = "generator expression"
		case *ast.Yield, *ast.YieldFrom:
			expr_name = "yield expression"
		case *ast.ListComp:
			expr_name = "list comprehension"
		case *ast.SetComp:
			expr_name = "set comprehension"
		case *ast.DictComp:
			expr_name = "dict comprehension"
		case *ast.Dict, *ast.Set, *ast.Num, *ast.Str, *ast.Bytes:
			expr_name = "literal"
		case *ast.NameConstant:
			expr_name = "keyword"
		case *ast.Ellipsis:
			expr_name = "Ellipsis"
		case *ast.Compare:
			expr_name = "comparison"
		case *ast.IfExp:
			expr_name = "conditional expression"
		default:
			expr_name = fmt.Sprintf("unexpected %T", expr)
		}
		action := "assign to"
		if ctx == ast.Del {
			action = "delete"
		}
		yylex.(*yyLex).SyntaxErrorf("can't %s %s", action, expr_name)
		return
	}
	setctxer.SetCtx(ctx)
}

// Set the context for all the items in exprs
func setCtxs(yylex yyLexer, exprs []ast.Expr, ctx ast.ExprContext) {
	for i := range exprs {
		setCtx(yylex, exprs[i], ctx)
	}
}

//line grammar.y:103
type yySymType struct {
	yys            int
	pos            ast.Pos // kept up to date by the lexer
	str            string
	obj            py.Object
	mod            ast.Mod
	stmt           ast.Stmt
	stmts          []ast.Stmt
	expr           ast.Expr
	exprs          []ast.Expr
	op             ast.OperatorNumber
	cmpop          ast.CmpOp
	comma          bool
	comprehensions []ast.Comprehension
	isExpr         bool
	slice          ast.Slicer
	call           *ast.Call
	level          int
	alias          *ast.Alias
	aliases        []*ast.Alias
	identifiers    []ast.Identifier
	ifstmt         *ast.If
	lastif         *ast.If
	exchandlers    []*ast.ExceptHandler
	withitem       *ast.WithItem
	withitems      []*ast.WithItem
	arg            *ast.Arg
	args           []*ast.Arg
	arguments      *ast.Arguments
}

const NEWLINE = 57346
const ENDMARKER = 57347
const NAME = 57348
const INDENT = 57349
const DEDENT = 57350
const STRING = 57351
const NUMBER = 57352
const PLINGEQ = 57353
const PERCEQ = 57354
const ANDEQ = 57355
const STARSTAR = 57356
const STARSTAREQ = 57357
const STAREQ = 57358
const PLUSEQ = 57359
const MINUSEQ = 57360
const MINUSGT = 57361
const ELIPSIS = 57362
const DIVDIV = 57363
const DIVDIVEQ = 57364
const DIVEQ = 57365
const LTLT = 57366
const LTLTEQ = 57367
const LTEQ = 57368
const LTGT = 57369
const EQEQ = 57370
const GTEQ = 57371
const GTGT = 57372
const GTGTEQ = 57373
const HATEQ = 57374
const PIPEEQ = 57375
const FALSE = 57376
const NONE = 57377
const TRUE = 57378
const AND = 57379
const AS = 57380
const ASSERT = 57381
const BREAK = 57382
const CLASS = 57383
const CONTINUE = 57384
const DEF = 57385
const DEL = 57386
const ELIF = 57387
const ELSE = 57388
const EXCEPT = 57389
const FINALLY = 57390
const FOR = 57391
const FROM = 57392
const GLOBAL = 57393
const IF = 57394
const IMPORT = 57395
const IN = 57396
const IS = 57397
const LAMBDA = 57398
const NONLOCAL = 57399
const NOT = 57400
const OR = 57401
const PASS = 57402
const RAISE = 57403
const RETURN = 57404
const TRY = 57405
const WHILE = 57406
const WITH = 57407
const YIELD = 57408
const SINGLE_INPUT = 57409
const FILE_INPUT = 57410
const EVAL_INPUT = 57411

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NEWLINE",
	"ENDMARKER",
	"NAME",
	"INDENT",
	"DEDENT",
	"STRING",
	"NUMBER",
	"PLINGEQ",
	"PERCEQ",
	"ANDEQ",
	"STARSTAR",
	"STARSTAREQ",
	"STAREQ",
	"PLUSEQ",
	"MINUSEQ",
	"MINUSGT",
	"ELIPSIS",
	"DIVDIV",
	"DIVDIVEQ",
	"DIVEQ",
	"LTLT",
	"LTLTEQ",
	"LTEQ",
	"LTGT",
	"EQEQ",
	"GTEQ",
	"GTGT",
	"GTGTEQ",
	"HATEQ",
	"PIPEEQ",
	"FALSE",
	"NONE",
	"TRUE",
	"AND",
	"AS",
	"ASSERT",
	"BREAK",
	"CLASS",
	"CONTINUE",
	"DEF",
	"DEL",
	"ELIF",
	"ELSE",
	"EXCEPT",
	"FINALLY",
	"FOR",
	"FROM",
	"GLOBAL",
	"IF",
	"IMPORT",
	"IN",
	"IS",
	"LAMBDA",
	"NONLOCAL",
	"NOT",
	"OR",
	"PASS",
	"RAISE",
	"RETURN",
	"TRY",
	"WHILE",
	"WITH",
	"YIELD",
	"'('",
	"')'",
	"'['",
	"']'",
	"':'",
	"','",
	"';'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'|'",
	"'&'",
	"'<'",
	"'>'",
	"'='",
	"'.'",
	"'%'",
	"'{'",
	"'}'",
	"'^'",
	"'~'",
	"'@'",
	"SINGLE_INPUT",
	"FILE_INPUT",
	"EVAL_INPUT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 232,
	68, 13,
	-2, 293,
	-1, 383,
	68, 93,
	-2, 294,
}

const yyPrivate = 57344

const yyLast = 1447

var yyAct = [...]int16{
	59, 471, 61, 314, 165, 97, 459, 321, 160, 164,
	424, 404, 350, 376, 362, 343, 259, 467, 223, 101,
	102, 140, 336, 111, 210, 335, 224, 103, 60, 6,
	318, 144, 231, 54, 237, 110, 69, 35, 95, 460,
	73, 66, 105, 150, 74, 71, 64, 145, 137, 107,
	72, 70, 57, 97, 142, 17, 180, 106, 189, 97,
	2, 3, 4, 175, 133, 107, 75, 288, 24, 146,
	23, 232, 277, 106, 247, 96, 379, 262, 173, 174,
	171, 172, 49, 152, 204, 246, 166, 327, 236, 181,
	284, 141, 179, 315, 163, 184, 185, 154, 99, 386,
	157, 423, 227, 226, 148, 477, 176, 178, 84, 167,
	177, 91, 85, 186, 187, 195, 48, 469, 215, 97,
	211, 188, 87, 388, 337, 279, 222, 280, 456, 453,
	247, 166, 169, 170, 196, 199, 90, 88, 89, 163,
	166, 281, 315, 190, 191, 192, 151, 393, 342, 401,
	312, 483, 234, 398, 251, 216, 162, 235, 252, 206,
	255, 385, 383, 422, 197, 200, 238, 260, 261, 81,
	239, 82, 374, 214, 400, 289, 76, 77, 63, 139,
	284, 257, 245, 258, 241, 334, 240, 83, 221, 358,
	78, 489, 243, 249, 333, 476, 159, 250, 463, 406,
	254, 162, 291, 253, 416, 263, 415, 455, 414, 412,
	341, 408, 311, 403, 380, 296, 371, 364, 316, 285,
	256, 97, 287, 269, 270, 290, 267, 111, 293, 271,
	272, 266, 268, 322, 219, 218, 283, 297, 298, 286,
	108, 357, 325, 399, 292, 328, 304, 382, 313, 373,
	107, 356, 354, 273, 274, 275, 276, 339, 106, 299,
	282, 232, 303, 344, 300, 305, 230, 340, 156, 284,
	238, 323, 462, 338, 239, 326, 155, 329, 248, 156,
	322, 351, 407, 156, 265, 264, 156, 220, 284, 284,
	359, 462, 360, 366, 368, 367, 244, 464, 410, 363,
	363, 134, 450, 394, 228, 158, 207, 34, 372, 307,
	347, 182, 355, 107, 15, 377, 378, 183, 315, 14,
	166, 106, 315, 166, 389, 302, 486, 370, 470, 211,
	468, 436, 375, 114, 315, 381, 166, 465, 433, 395,
	116, 384, 337, 390, 345, 117, 260, 397, 136, 353,
	331, 330, 146, 405, 324, 295, 294, 392, 396, 138,
	391, 135, 387, 113, 112, 217, 98, 212, 100, 417,
	7, 402, 213, 309, 308, 229, 411, 310, 161, 109,
	425, 426, 301, 413, 322, 361, 428, 429, 332, 430,
	420, 427, 421, 143, 418, 147, 211, 149, 317, 454,
	409, 320, 351, 319, 439, 349, 348, 441, 435, 443,
	442, 444, 434, 431, 437, 438, 432, 440, 168, 124,
	125, 242, 130, 122, 120, 121, 377, 452, 446, 131,
	123, 445, 128, 447, 448, 449, 451, 25, 129, 127,
	126, 457, 119, 193, 203, 104, 461, 205, 306, 365,
	202, 458, 233, 68, 473, 62, 80, 278, 79, 118,
	16, 115, 466, 13, 12, 472, 435, 11, 9, 10,
	322, 44, 478, 43, 42, 481, 41, 479, 482, 40,
	39, 487, 475, 484, 38, 488, 472, 33, 32, 132,
	490, 491, 472, 31, 30, 485, 209, 208, 84, 29,
	28, 91, 85, 27, 26, 369, 8, 93, 94, 5,
	92, 1, 87, 86, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 90, 88, 89, 0,
	0, 47, 50, 24, 51, 23, 36, 0, 0, 0,
	0, 20, 56, 45, 18, 55, 0, 0, 65, 46,
	67, 0, 37, 53, 52, 21, 19, 22, 58, 81,
	84, 82, 419, 91, 85, 0, 76, 77, 63, 0,
	0, 0, 0, 0, 87, 0, 0, 83, 0, 0,
	78, 48, 0, 0, 0, 0, 0, 0, 90, 88,
	89, 0, 0, 47, 50, 24, 51, 23, 36, 0,
	0, 0, 0, 20, 56, 45, 18, 55, 0, 0,
	65, 46, 67, 0, 37, 53, 52, 21, 19, 22,
	58, 81, 84, 82, 0, 91, 85, 0, 76, 77,
	63, 0, 0, 0, 0, 0, 87, 0, 0, 83,
	0, 0, 78, 48, 0, 0, 0, 0, 0, 0,
	90, 88, 89, 0, 0, 47, 50, 24, 51, 23,
	36, 0, 0, 0, 0, 20, 56, 45, 18, 55,
	0, 0, 65, 46, 67, 0, 37, 53, 52, 21,
	19, 22, 58, 81, 0, 82, 0, 0, 0, 0,
	76, 77, 63, 225, 0, 84, 0, 0, 91, 85,
	0, 83, 0, 0, 78, 48, 0, 0, 0, 87,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 90, 88, 89, 0, 0, 47, 50,
	0, 51, 0, 36, 0, 0, 0, 0, 0, 56,
	45, 0, 55, 0, 0, 65, 46, 67, 0, 37,
	53, 52, 0, 0, 0, 58, 81, 84, 82, 0,
	91, 85, 0, 76, 77, 63, 0, 0, 0, 0,
	0, 87, 0, 0, 83, 0, 0, 78, 0, 0,
	0, 0, 0, 0, 0, 90, 88, 89, 0, 0,
	47, 50, 0, 51, 0, 36, 0, 0, 0, 0,
	0, 56, 45, 0, 55, 0, 0, 65, 46, 67,
	0, 37, 53, 52, 0, 0, 0, 58, 81, 84,
	82, 0, 91, 85, 0, 76, 77, 63, 0, 0,
	0, 0, 0, 87, 0, 0, 83, 0, 0, 78,
	0, 0, 0, 0, 0, 0, 0, 90, 88, 89,
	0, 0, 0, 0, 0, 0, 84, 0, 0, 91,
	85, 0, 0, 0, 0, 0, 0, 0, 0, 65,
	87, 67, 0, 0, 0, 0, 0, 0, 0, 58,
	81, 194, 82, 0, 90, 88, 89, 76, 77, 63,
	0, 0, 0, 84, 0, 0, 91, 85, 83, 0,
	0, 78, 0, 0, 0, 0, 65, 87, 67, 0,
	0, 0, 0, 0, 0, 0, 58, 81, 0, 82,
	0, 90, 88, 89, 76, 77, 63, 0, 0, 0,
	0, 0, 0, 0, 0, 83, 84, 0, 78, 91,
	85, 0, 0, 65, 480, 67, 0, 0, 0, 0,
	87, 0, 0, 0, 81, 0, 82, 198, 0, 0,
	0, 76, 77, 63, 90, 88, 89, 0, 0, 0,
	0, 0, 83, 84, 0, 78, 91, 85, 0, 0,
	0, 0, 0, 0, 0, 0, 65, 87, 67, 0,
	0, 0, 0, 0, 0, 0, 0, 81, 0, 82,
	0, 90, 88, 89, 76, 77, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 83, 84, 0, 78, 91,
	85, 0, 0, 65, 0, 67, 0, 0, 0, 0,
	87, 0, 0, 0, 81, 0, 82, 0, 406, 0,
	0, 76, 77, 0, 90, 88, 89, 0, 0, 0,
	0, 0, 83, 0, 0, 78, 0, 0, 84, 0,
	0, 91, 85, 0, 0, 0, 65, 0, 67, 0,
	0, 0, 87, 0, 0, 0, 0, 81, 0, 82,
	0, 352, 0, 0, 76, 77, 90, 88, 89, 0,
	0, 0, 0, 0, 0, 83, 0, 0, 78, 0,
	84, 0, 0, 91, 85, 0, 0, 0, 65, 0,
	67, 0, 0, 0, 87, 0, 0, 0, 0, 81,
	346, 82, 0, 0, 0, 0, 76, 77, 90, 88,
	89, 0, 0, 0, 0, 0, 0, 83, 0, 0,
	78, 0, 0, 84, 0, 0, 91, 85, 0, 0,
	65, 0, 67, 0, 0, 0, 0, 87, 0, 0,
	0, 81, 0, 82, 0, 0, 0, 0, 76, 77,
	63, 90, 88, 89, 0, 0, 0, 0, 0, 83,
	84, 0, 78, 91, 85, 0, 0, 0, 0, 0,
	0, 0, 0, 65, 87, 67, 0, 0, 0, 0,
	0, 0, 0, 58, 81, 0, 82, 0, 90, 88,
	89, 76, 77, 0, 0, 0, 0, 84, 0, 0,
	91, 85, 83, 0, 0, 78, 0, 0, 0, 0,
	65, 87, 67, 0, 0, 0, 0, 0, 0, 0,
	0, 81, 0, 82, 0, 90, 88, 89, 76, 77,
	0, 0, 0, 0, 84, 0, 0, 91, 85, 83,
	201, 153, 78, 0, 0, 0, 0, 65, 87, 67,
	0, 0, 0, 0, 0, 0, 0, 0, 81, 0,
	82, 0, 90, 88, 89, 76, 77, 0, 0, 0,
	0, 84, 0, 0, 91, 85, 83, 0, 0, 78,
	0, 0, 0, 0, 474, 87, 67, 0, 0, 0,
	0, 0, 0, 0, 0, 81, 0, 82, 0, 90,
	88, 89, 76, 77, 0, 0, 0, 0, 84, 0,
	0, 91, 85, 83, 0, 0, 78, 0, 0, 0,
	0, 65, 87, 67, 0, 0, 0, 0, 0, 0,
	0, 0, 81, 0, 82, 0, 90, 88, 89, 76,
	77, 0, 0, 0, 84, 0, 0, 91, 85, 0,
	83, 0, 0, 78, 0, 0, 0, 0, 87, 0,
	67, 0, 0, 0, 0, 0, 0, 0, 0, 81,
	0, 82, 90, 88, 89, 0, 76, 77, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 83, 0, 0,
	78, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 81, 0, 82, 0, 0,
	0, 0, 76, 77, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 83, 0, 0, 78,
}

var yyPact = [...]int16{
	-30, -1000, 616, -1000, 1285, -1000, -1000, 362, 25, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 1285, 1285,
	102, 169, 1285, 358, 357, 27, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 407, 102, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 355, 355, 1285, 353, 107,
	-1000, -1000, 1285, 1285, -1000, 346, 63, -1000, 1211, -1000,
	-1000, 224, -1000, 1358, 268, 125, -1000, 1322, 52, 14,
	-31, 10, 287, 21, 37, -1000, 1358, 1358, 1358, -1000,
	-1000, 813, 887, 1174, -1000, -1000, 297, -1000, -1000, -1000,
	-1000, -1000, -1000, 492, -1000, -1000, 101, -1000, -1000, 751,
	361, 164, 163, 233, 116, -1000, 14, -1000, 689, 31,
	-1000, 266, 199, 194, -1000, -1000, -1000, -1000, 1137, 6,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 850, -1000, 114, -1000, 114, 112, -1000, 1094,
	-1000, -1000, 246, 110, -1000, 47, -1000, 225, -9, 63,
	-1000, -1000, -1000, 1285, -1000, 1322, 1322, 14, 1322, 1285,
	149, 109, 330, 330, -1000, -5, -1000, -1000, 1358, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 231, 226, 1358,
	1358, 1358, 1358, 1358, 1358, 1358, 1358, 1358, 1358, 1358,
	-1000, -1000, -1000, 58, -1000, 192, 240, 107, -1000, 240,
	107, -1000, -19, 103, 131, -1000, 101, -1000, -1000, -1000,
	-1000, -1000, -1000, 351, 1285, -1000, -1000, -1000, 689, 689,
	1285, 102, -1000, -1000, -1000, 318, 1285, 689, 1358, 290,
	136, 147, 1285, -1000, -1000, -1000, 850, -1000, -1000, -1000,
	348, 1285, 4, -1000, 1285, 346, 345, 344, 118, -1000,
	-9, -1000, 227, 268, -1000, -1000, 1285, 134, -1000, -1000,
	-1000, -1000, 1285, 14, -1000, -1000, -31, 10, 287, 21,
	21, 37, 37, -1000, -1000, -1000, -1000, 1358, -1000, 1052,
	1010, 343, -1000, 184, 102, 183, 171, 119, -1000, 1285,
	-1000, 1285, -1000, -1000, -1000, -1000, -1000, -1000, 254, 146,
	-1000, 247, 616, -1000, -1000, 14, 145, 1285, 181, -1000,
	100, 328, 328, -1000, -6, 143, 689, 179, -1000, 90,
	85, -1000, 41, -1000, -1000, -1000, 320, 337, -1000, -1000,
	-1000, -1000, -1000, -1000, 336, 75, -1000, 265, 1285, -1000,
	-1000, 330, 330, 81, -1000, -1000, -1000, 175, 104, 77,
	-1000, 142, 967, -1000, -1000, 228, -1000, -1000, -1000, 140,
	240, 253, -1000, 138, 689, 137, 135, 133, 1285, 554,
	-1000, 689, -1000, -1000, 87, -1000, -1000, -1000, -1000, 1285,
	1285, -1000, -1000, 1285, -1000, 1285, 1285, -1000, 1285, -1000,
	-1000, 75, -1000, 336, 332, -1000, -1000, -1000, 317, -1000,
	-1000, 1010, -1000, 967, -1000, 128, 1285, 1322, 1285, -1000,
	1285, -1000, 689, 254, 689, 689, 689, 264, -1000, -1000,
	-1000, -1000, 328, 328, 57, -1000, -1000, -1000, -1000, -1000,
	-1000, 139, -1000, -1000, 56, -1000, 330, -1000, -1000, 128,
	-1000, -1000, 220, -1000, 127, -1000, -1000, -1000, 249, -1000,
	331, -1000, -1000, 316, 45, -1000, 314, -1000, -1000, -1000,
	-1000, -1000, 1248, 689, 124, -1000, 33, -1000, 328, 930,
	330, 239, 209, -1000, 80, -1000, 689, 312, -1000, -1000,
	1285, -1000, -1000, 1248, 120, -1000, 328, -1000, -1000, 1248,
	-1000, -1000,
}

var yyPgo = [...]int16{
	0, 513, 511, 510, 509, 508, 26, 24, 507, 506,
	505, 18, 14, 367, 55, 504, 503, 500, 499, 494,
	493, 488, 487, 484, 480, 479, 476, 474, 473, 471,
	469, 468, 467, 464, 463, 319, 314, 461, 460, 459,
	42, 36, 28, 51, 45, 50, 40, 44, 66, 458,
	457, 456, 52, 0, 41, 455, 1, 454, 2, 46,
	453, 38, 37, 452, 33, 34, 450, 11, 449, 448,
	307, 27, 447, 446, 6, 445, 82, 75, 444, 443,
	442, 437, 421, 418, 21, 39, 12, 406, 405, 7,
	403, 401, 399, 30, 32, 398, 43, 397, 47, 395,
	301, 31, 22, 393, 25, 388, 385, 382, 35, 379,
	9, 4, 16, 17, 3, 13, 15, 378, 10, 377,
	8, 375, 374, 373, 372, 368,
}

var yyR1 = [...]int8{
	0, 2, 2, 2, 4, 4, 3, 8, 8, 8,
	5, 124, 124, 95, 95, 94, 94, 70, 82, 82,
	81, 81, 37, 37, 38, 69, 69, 35, 121, 122,
	122, 113, 113, 118, 118, 119, 119, 115, 115, 123,
	123, 123, 123, 123, 123, 123, 114, 114, 110, 110,
	116, 116, 117, 117, 112, 112, 120, 120, 120, 120,
	120, 120, 120, 111, 7, 7, 125, 125, 9, 9,
	6, 14, 14, 14, 14, 14, 14, 14, 14, 15,
	15, 15, 63, 63, 65, 65, 80, 80, 76, 76,
	52, 52, 84, 84, 62, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 16, 17, 18,
	18, 18, 18, 18, 23, 24, 25, 25, 27, 26,
	26, 26, 19, 19, 28, 96, 96, 97, 97, 99,
	99, 99, 105, 105, 105, 29, 102, 102, 101, 101,
	104, 104, 103, 103, 98, 98, 100, 100, 20, 21,
	77, 77, 22, 22, 13, 13, 13, 13, 13, 13,
	13, 13, 106, 106, 12, 12, 31, 30, 32, 107,
	107, 33, 33, 33, 33, 109, 109, 34, 108, 108,
	68, 68, 68, 10, 10, 11, 11, 53, 53, 53,
	56, 56, 55, 55, 57, 57, 58, 58, 59, 59,
	54, 54, 60, 60, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 42, 41, 41, 43, 43,
	44, 44, 45, 45, 45, 46, 46, 46, 47, 47,
	47, 47, 47, 48, 48, 48, 48, 49, 49, 79,
	79, 1, 1, 51, 51, 51, 51, 51, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 51, 50,
	50, 50, 50, 88, 88, 87, 86, 86, 86, 86,
	86, 86, 86, 86, 86, 67, 67, 40, 40, 75,
	75, 71, 61, 72, 78, 78, 66, 66, 66, 66,
	36, 90, 90, 91, 91, 92, 92, 93, 93, 93,
	93, 89, 89, 89, 74, 74, 85, 85, 73, 73,
	64, 64, 64,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 1, 2, 2, 0, 2, 2,
	3, 0, 2, 0, 1, 0, 3, 5, 0, 3,
	1, 2, 1, 1, 2, 0, 2, 6, 3, 0,
	1, 1, 3, 0, 3, 1, 3, 0, 1, 2,
	5, 8, 4, 3, 6, 2, 1, 3, 1, 3,
	0, 3, 1, 3, 0, 1, 2, 5, 8, 4,
	3, 6, 2, 1, 1, 1, 0, 1, 1, 3,
	3, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	2, 1, 1, 1, 1, 1, 2, 3, 1, 3,
	1, 1, 0, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
	2, 4, 1, 1, 2, 1, 1, 1, 2, 1,
	2, 1, 1, 4, 2, 4, 1, 3, 1, 3,
	1, 3, 1, 3, 1, 3, 1, 3, 2, 2,
	1, 3, 2, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 5, 0, 3, 6, 5, 7, 0,
	4, 4, 7, 7, 10, 1, 3, 4, 1, 3,
	1, 2, 4, 1, 2, 1, 4, 1, 5, 1,
	1, 1, 3, 4, 3, 4, 1, 3, 1, 3,
	2, 1, 1, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 2, 2, 1, 3, 1, 3,
	1, 3, 1, 3, 3, 1, 3, 3, 1, 3,
	3, 3, 3, 2, 2, 2, 1, 2, 4, 0,
	2, 1, 2, 2, 3, 4, 4, 2, 4, 4,
	2, 3, 1, 1, 1, 1, 1, 1, 1, 2,
	3, 3, 2, 1, 3, 2, 1, 1, 2, 2,
	3, 2, 3, 3, 4, 1, 2, 1, 1, 1,
	3, 2, 2, 2, 3, 5, 2, 4, 1, 2,
	5, 1, 3, 0, 2, 0, 3, 2, 4, 7,
	3, 1, 2, 3, 1, 1, 4, 5, 2, 3,
	1, 3, 2,
}

var yyChk = [...]int16{
	-1000, -2, 90, 91, 92, -4, -6, -13, -9, -31,
	-30, -32, -33, -34, -35, -36, -38, -14, 52, 64,
	49, 63, 65, 43, 41, -81, -15, -16, -17, -18,
	-19, -20, -21, -22, -70, -62, 44, 60, -23, -24,
	-25, -26, -27, -28, -29, 51, 57, 39, 89, -76,
	40, 42, 62, 61, -64, 53, 50, -52, 66, -53,
	-42, -58, -55, 76, -59, 56, -54, 58, -60, -41,
	-43, -44, -45, -46, -47, -48, 74, 75, 88, -49,
	-51, 67, 69, 85, 6, 10, -1, 20, 35, 36,
	34, 9, -3, -8, -5, -61, -77, -53, 4, 73,
	-125, -53, -53, -71, -75, -40, -41, -42, 71, -109,
	-108, -53, 6, 6, -70, -37, -36, -35, -39, -80,
	17, 18, 16, 23, 12, 13, 33, 32, 25, 31,
	15, 22, 82, -71, -100, 6, -100, -53, 6, 72,
	-84, -61, -53, -103, -101, -98, 6, -99, -98, -97,
	-96, 83, 20, 50, -61, 52, 59, -41, 37, 71,
	-120, -117, 76, 14, -110, -111, 6, -54, -83, 80,
	81, 28, 29, 26, 27, 11, 54, 58, 55, 78,
	87, 79, 24, 30, 74, 75, 76, 77, 84, 21,
	-48, -48, -48, -79, 68, -64, -52, -76, 70, -52,
	-76, 86, -66, -78, -53, -72, -77, 9, 5, 4,
	-7, -6, -13, -124, 72, -84, -14, 4, 71, 71,
	54, 72, -84, -11, -6, 4, 72, 71, 38, -121,
	67, -94, 67, -63, -64, -61, 82, -65, -64, -62,
	72, 72, -82, -52, 50, 72, 38, 83, 53, -96,
	-98, -53, -58, -59, -54, -53, 71, 72, -84, -112,
	-111, -111, 82, -41, 54, 58, -43, -44, -45, -46,
	-46, -47, -47, -48, -48, -48, -48, 14, -50, 67,
	69, 83, 68, -85, 49, -84, -85, -84, 86, 72,
	-84, 71, -85, -84, 5, 4, -53, -11, -11, -61,
	-40, -107, 7, -108, -11, -41, -69, 19, -122, -123,
	-119, 76, 14, -113, -114, 6, 71, -95, -93, -90,
	-91, -89, -53, -65, 6, -53, -94, 83, -53, -101,
	6, 6, -105, 76, 67, -104, -102, 6, 46, -53,
	-110, 76, 14, -116, -53, -48, 68, -93, -87, -88,
	-86, -53, 71, 6, 68, -71, 68, 70, 70, -53,
	-53, -106, -12, 46, 71, -68, 46, 48, 47, -10,
	-7, 71, -53, 68, 72, -84, -115, -114, -114, 82,
	71, -11, 68, 72, -84, 76, 14, -85, 82, 4,
	6, -104, -84, 72, 38, -53, -112, -111, 72, 68,
	70, 72, -84, 71, -67, -53, 71, 54, 71, -85,
	45, -12, 71, -11, 71, 71, 71, -53, -7, 8,
	-11, -113, 76, 14, -118, -53, -53, -89, -53, -53,
	-53, -84, -102, 6, -116, -110, 14, -86, -67, -53,
	-67, -53, -58, -53, -53, -11, -12, -11, -11, -11,
	38, -115, -114, 72, -92, 68, 72, -111, -67, -74,
	-85, -73, 52, 71, 48, 6, -118, -113, 14, 72,
	14, -56, -58, -57, 56, -11, 71, 72, -114, -89,
	14, -111, -74, 71, -120, -11, 14, -53, -56, 71,
	-114, -56,
}

var yyDef = [...]int16{
	0, -2, 0, 7, 0, 1, 4, 0, 66, 154,
	155, 156, 157, 158, 159, 160, 161, 68, 0, 0,
	0, 0, 0, 0, 0, 0, 71, 72, 73, 74,
	75, 76, 77, 78, 20, 81, 0, 108, 109, 110,
	111, 112, 113, 122, 123, 0, 0, 0, 0, 92,
	114, 115, 116, 119, 118, 0, 0, 88, 310, 90,
	91, 187, 189, 0, 196, 0, 198, 0, 201, 202,
	216, 218, 220, 222, 225, 228, 0, 0, 0, 236,
	239, 0, 0, 0, 252, 253, 254, 255, 256, 257,
	258, 241, 2, 0, 3, 11, 92, 150, 5, 67,
	0, 0, 0, 0, 92, 279, 277, 278, 0, 0,
	175, 178, 0, 15, 21, 24, 22, 23, 0, 80,
	95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
	105, 106, 0, 107, 148, 146, 149, 152, 18, 93,
	94, 117, 120, 124, 142, 138, 144, 0, 129, 131,
	127, 125, 126, 0, 312, 0, 0, 215, 0, 0,
	0, 92, 54, 0, 52, 48, 63, 200, 0, 204,
	205, 206, 207, 208, 209, 210, 211, 0, 213, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	233, 234, 235, 237, 243, 0, 88, 92, 247, 88,
	92, 250, 0, 92, 150, 288, 92, 242, 6, 8,
	9, 64, 65, 0, 93, 282, 69, 70, 0, 0,
	0, 93, 281, 169, 185, 0, 0, 0, 0, 25,
	29, 0, -2, 79, 82, 83, 0, 86, 84, 85,
	0, 0, 15, 89, 0, 0, 0, 0, 0, 128,
	130, 311, 0, 197, 199, 192, 0, 93, 56, 50,
	55, 62, 0, 203, 212, 214, 217, 219, 221, 223,
	224, 226, 227, 229, 230, 231, 232, 0, 240, 293,
	0, 0, 244, 0, 0, 0, 0, 0, 251, 93,
	286, 0, 289, 283, 10, 12, 151, 162, 164, 0,
	280, 171, 0, 176, 177, 179, 0, 0, 0, 30,
	92, 37, 0, 35, 31, 46, 0, 0, 14, 92,
	0, 291, 301, 87, 147, 153, 0, 0, 121, 143,
	139, 145, 135, 132, 0, 92, 140, 136, 0, 193,
	53, 54, 0, 60, 49, 238, 259, 0, 0, 92,
	263, 266, 267, 262, 245, 0, 246, 248, 249, 0,
	284, 164, 167, 0, 0, 0, 0, 0, 180, 0,
	183, 0, 26, 28, 93, 39, 33, 38, 45, 0,
	0, 290, 16, -2, 297, 0, 0, 302, 0, 17,
	19, 92, 134, 93, 0, 188, 50, 59, 0, 260,
	261, 93, 265, 271, 268, 269, 275, 0, 0, 287,
	0, 166, 0, 164, 0, 0, 0, 181, 184, 186,
	27, 36, 37, 0, 43, 32, 47, 292, 295, 300,
	303, 0, 141, 137, 57, 51, 0, 264, 272, 273,
	270, 276, 306, 285, 0, 165, 168, 170, 172, 173,
	0, 33, 42, 0, 298, 133, 0, 61, 274, 307,
	304, 305, 0, 0, 0, 182, 40, 34, 0, 0,
	0, 308, 190, 191, 0, 163, 0, 0, 44, 296,
	0, 58, 309, 0, 0, 174, 0, 299, 194, 0,
	41, 195,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 84, 79, 3,
	67, 68, 76, 74, 72, 75, 83, 77, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 71, 73,
	80, 82, 81, 3, 89, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 69, 3, 70, 87, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 85, 78, 86, 88,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 90, 91, 92,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:250
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:255
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:260
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:274
		{
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:278
		{
			//  NB: compound_stmt in single_input is followed by extra NEWLINE!
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: []ast.Stmt{yyDollar[1].stmt}}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:286
		{
			yyVAL.mod = &ast.Module{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:292
		{
			yyVAL.stmts = nil
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:296
		{
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:299
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:306
		{
			yyVAL.mod = &ast.Expression{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].expr}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:315
		{
			yyVAL.call = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:319
		{
			yyVAL.call = yyDollar[1].call
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:324
		{
			yyVAL.call = nil
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:328
		{
			yyVAL.call = yyDollar[2].call
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:334
		{
			var name ast.Expr = &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
			if yyDollar[3].exprs != nil {
				name = applyTrailers(name, yyDollar[3].exprs)
			}
			if yyDollar[4].call != nil {
				name = applyTrailers(name, []ast.Expr{yyDollar[4].call})
			}
			yyVAL.expr = name
		}
	case 18:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:346
		{
			yyVAL.exprs = nil
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:350
		{
			yyVAL.exprs = append(yyVAL.exprs, &ast.Attribute{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Attr: ast.Identifier(yyDollar[3].str), Ctx: ast.Load})
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:356
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:361
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:367
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:371
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:377
		{
			switch x := (yyDollar[2].stmt).(type) {
			case *ast.ClassDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			case *ast.FunctionDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			default:
				panic("bad type for decorated")
			}
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:391
		{
			yyVAL.expr = nil
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:395
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 27:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:401
		{
			yyVAL.stmt = &ast.FunctionDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Args: yyDollar[3].arguments, Body: yyDollar[6].stmts, Returns: yyDollar[4].expr}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:407
		{
			yyVAL.arguments = yyDollar[2].arguments
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:412
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:416
		{
			yyVAL.arguments = yyDollar[1].arguments
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:423
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:428
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 33:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:434
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:439
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:448
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:457
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:465
		{
			yyVAL.arg = nil
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:469
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:476
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:480
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 41:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:484
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:488
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:492
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 44:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:496
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:500
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:506
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:510
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str), Annotation: yyDollar[3].expr}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:516
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:521
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:527
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:532
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:541
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:550
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 54:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:558
		{
			yyVAL.arg = nil
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:562
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:569
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 57:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:573
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 58:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:577
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 59:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:581
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:585
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 61:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:589
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:593
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:599
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:605
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:609
		{
			yyVAL.stmts = []ast.Stmt{yyDollar[1].stmt}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:617
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmt)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:622
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[3].stmt)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:628
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:634
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:638
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:642
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:646
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:650
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:654
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:658
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:662
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:689
		{
			target := yyDollar[1].expr
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.AugAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Op: yyDollar[2].op, Value: yyDollar[3].expr}
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:695
		{
			targets := []ast.Expr{yyDollar[1].expr}
			targets = append(targets, yyDollar[2].exprs...)
			value := targets[len(targets)-1]
			targets = targets[:len(targets)-1]
			setCtxs(yylex, targets, ast.Store)
			yyVAL.stmt = &ast.Assign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: targets, Value: value}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:704
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:710
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:714
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:720
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:724
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:730
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:735
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:741
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:746
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:752
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:756
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:761
		{
			yyVAL.comma = false
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:765
		{
			yyVAL.comma = true
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:771
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[1].exprs, yyDollar[2].comma)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:777
		{
			yyVAL.op = ast.Add
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:781
		{
			yyVAL.op = ast.Sub
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:785
		{
			yyVAL.op = ast.Mult
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:789
		{
			yyVAL.op = ast.Div
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:793
		{
			yyVAL.op = ast.Modulo
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:797
		{
			yyVAL.op = ast.BitAnd
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:801
		{
			yyVAL.op = ast.BitOr
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:805
		{
			yyVAL.op = ast.BitXor
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:809
		{
			yyVAL.op = ast.LShift
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:813
		{
			yyVAL.op = ast.RShift
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:817
		{
			yyVAL.op = ast.Pow
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:821
		{
			yyVAL.op = ast.FloorDiv
		}
	case 107:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:828
		{
			setCtxs(yylex, yyDollar[2].exprs, ast.Del)
			yyVAL.stmt = &ast.Delete{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: yyDollar[2].exprs}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:835
		{
			yyVAL.stmt = &ast.Pass{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:841
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:845
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:849
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:853
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:857
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:863
		{
			yyVAL.stmt = &ast.Break{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:869
		{
			yyVAL.stmt = &ast.Continue{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:875
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:879
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:885
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:891
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:895
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr}
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:899
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr, Cause: yyDollar[4].expr}
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:905
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:909
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:915
		{
			yyVAL.stmt = &ast.Import{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].aliases}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:922
		{
			yyVAL.level = 1
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:926
		{
			yyVAL.level = 3
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:932
		{
			yyVAL.level = yyDollar[1].level
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:936
		{
			yyVAL.level += yyDollar[2].level
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:942
		{
			yyVAL.level = 0
			yyVAL.str = yyDollar[1].str
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:947
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = yyDollar[2].str
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:952
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = ""
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:959
		{
			yyVAL.aliases = []*ast.Alias{&ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier("*")}}
		}
	case 133:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:963
		{
			yyVAL.aliases = yyDollar[2].aliases
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:967
		{
			yyVAL.aliases = yyDollar[1].aliases
		}
	case 135:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:973
		{
			yyVAL.stmt = &ast.ImportFrom{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Module: ast.Identifier(yyDollar[2].str), Names: yyDollar[4].aliases, Level: yyDollar[2].level}
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:979
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:983
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:989
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:993
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:999
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1004
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1010
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1015
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1021
		{
			yyVAL.str = yyDollar[1].str
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1025
		{
			yyVAL.str += "." + yyDollar[3].str
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1031
		{
			yyVAL.identifiers = nil
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[1].str))
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1036
		{
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[3].str))
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1042
		{
			yyVAL.stmt = &ast.Global{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1048
		{
			yyVAL.stmt = &ast.Nonlocal{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1054
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1059
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1065
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr}
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1069
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Msg: yyDollar[4].expr}
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1075
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1079
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1083
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1087
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1091
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1095
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1099
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1103
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1108
		{
			yyVAL.ifstmt = nil
			yyVAL.lastif = nil
		}
	case 163:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1113
		{
			elifs := yyVAL.ifstmt
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[5].stmts}
			if elifs == nil {
				yyVAL.ifstmt = newif
			} else {
				yyVAL.lastif.Orelse = []ast.Stmt{newif}
			}
			yyVAL.lastif = newif
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1125
		{
			yyVAL.stmts = nil
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1129
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 166:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:1135
		{
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts}
			yyVAL.stmt = newif
			elifs := yyDollar[5].ifstmt
			optional_else := yyDollar[6].stmts
			if len(optional_else) != 0 {
				if elifs != nil {
					yyDollar[5].lastif.Orelse = optional_else
					newif.Orelse = []ast.Stmt{elifs}
				} else {
					newif.Orelse = optional_else
				}
			} else {
				if elifs != nil {
					newif.Orelse = []ast.Stmt{elifs}
				}
			}
		}
	case 167:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1156
		{
			yyVAL.stmt = &ast.While{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts, Orelse: yyDollar[5].stmts}
		}
	case 168:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:1162
		{
			target := tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, false)
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.For{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Iter: yyDollar[4].expr, Body: yyDollar[6].stmts, Orelse: yyDollar[7].stmts}
		}
	case 169:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1169
		{
			yyVAL.exchandlers = nil
		}
	case 170:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1173
		{
			exc := &ast.ExceptHandler{Pos: yyVAL.pos, ExprType: yyDollar[2].expr, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[4].stmts}
			yyVAL.exchandlers = append(yyVAL.exchandlers, exc)
		}
	case 171:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1180
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers}
		}
	case 172:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:1184
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts}
		}
	case 173:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:1188
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Finalbody: yyDollar[7].stmts}
		}
	case 174:
		yyDollar = yyS[yypt-10 : yypt+1]
//line grammar.y:1192
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts, Finalbody: yyDollar[10].stmts}
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1198
		{
			yyVAL.withitems = nil
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[1].withitem)
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1203
		{
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[3].withitem)
		}
	case 177:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1209
		{
			yyVAL.stmt = &ast.With{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Items: yyDollar[2].withitems, Body: yyDollar[4].stmts}
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1215
		{
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr}
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1219
		{
			v := yyDollar[3].expr
			setCtx(yylex, v, ast.Store)
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr, OptionalVars: v}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1228
		{
			yyVAL.expr = nil
			yyVAL.str = ""
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1233
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = ""
		}
	case 182:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1238
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = yyDollar[4].str
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1245
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmts...)
		}
	case 184:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1250
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1256
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1260
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1266
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 188:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1270
		{
			yyVAL.expr = &ast.IfExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[1].expr, Orelse: yyDollar[5].expr}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1274
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1280
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1284
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 192:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1290
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1295
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1301
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1306
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1312
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1317
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Or, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1329
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1334
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.And, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1346
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Not, Operand: yyDollar[2].expr}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1350
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1356
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1361
		{
			if !yyDollar[1].isExpr {
				comp := yyVAL.expr.(*ast.Compare)
				comp.Ops = append(comp.Ops, yyDollar[2].cmpop)
				comp.Comparators = append(comp.Comparators, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.Compare{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyVAL.expr, Ops: []ast.CmpOp{yyDollar[2].cmpop}, Comparators: []ast.Expr{yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1376
		{
			yyVAL.cmpop = ast.Lt
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1380
		{
			yyVAL.cmpop = ast.Gt
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1384
		{
			yyVAL.cmpop = ast.Eq
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1388
		{
			yyVAL.cmpop = ast.GtE
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1392
		{
			yyVAL.cmpop = ast.LtE
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1396
		{
			yylex.(*yyLex).SyntaxError("invalid syntax")
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1400
		{
			yyVAL.cmpop = ast.NotEq
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1404
		{
			yyVAL.cmpop = ast.In
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1408
		{
			yyVAL.cmpop = ast.NotIn
		}
	case 213:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1412
		{
			yyVAL.cmpop = ast.Is
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1416
		{
			yyVAL.cmpop = ast.IsNot
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1422
		{
			yyVAL.expr = &ast.Starred{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr, Ctx: ast.Load}
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1428
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1432
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitOr, Right: yyDollar[3].expr}
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1438
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 219:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1442
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitXor, Right: yyDollar[3].expr}
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1448
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1452
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitAnd, Right: yyDollar[3].expr}
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1458
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 223:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1462
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.LShift, Right: yyDollar[3].expr}
		}
	case 224:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1466
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.RShift, Right: yyDollar[3].expr}
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1472
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1476
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Add, Right: yyDollar[3].expr}
		}
	case 227:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1480
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Sub, Right: yyDollar[3].expr}
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1486
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 229:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1490
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Mult, Right: yyDollar[3].expr}
		}
	case 230:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1494
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Div, Right: yyDollar[3].expr}
		}
	case 231:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1498
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Modulo, Right: yyDollar[3].expr}
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1502
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.FloorDiv, Right: yyDollar[3].expr}
		}
	case 233:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1508
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.UAdd, Operand: yyDollar[2].expr}
		}
	case 234:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1512
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.USub, Operand: yyDollar[2].expr}
		}
	case 235:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1516
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Invert, Operand: yyDollar[2].expr}
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1520
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 237:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1526
		{
			yyVAL.expr = applyTrailers(yyDollar[1].expr, yyDollar[2].exprs)
		}
	case 238:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1530
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: applyTrailers(yyDollar[1].expr, yyDollar[2].exprs), Op: ast.Pow, Right: yyDollar[4].expr}
		}
	case 239:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1536
		{
			yyVAL.exprs = nil
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1540
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1546
		{
			yyVAL.obj = yyDollar[1].obj
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1550
		{
			switch a := yyVAL.obj.(type) {
			case py.String:
				switch b := yyDollar[2].obj.(type) {
				case py.String:
					yyVAL.obj = a + b
				default:
					yylex.(*yyLex).SyntaxError("cannot mix string and nonstring literals")
				}
			case py.Bytes:
				switch b := yyDollar[2].obj.(type) {
				case py.Bytes:
					yyVAL.obj = append(a, b...)
				default:
					yylex.(*yyLex).SyntaxError("cannot mix bytes and nonbytes literals")
				}
			}
		}
	case 243:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1571
		{
			yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 244:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1575
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 245:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1579
		{
			yyVAL.expr = &ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 246:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1583
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[3].comma)
		}
	case 247:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1587
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 248:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1591
		{
			yyVAL.expr = &ast.ListComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 249:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1595
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[2].exprs, Ctx: ast.Load}
		}
	case 250:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1599
		{
			yyVAL.expr = &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 251:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1603
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 252:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1607
		{
			yyVAL.expr = &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[1].str), Ctx: ast.Load}
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1611
		{
			yyVAL.expr = &ast.Num{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, N: yyDollar[1].obj}
		}
	case 254:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1615
		{
			switch s := yyDollar[1].obj.(type) {
			case py.String:
				yyVAL.expr = &ast.Str{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			case py.Bytes:
				yyVAL.expr = &ast.Bytes{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			default:
				panic("not Bytes or String in strings")
			}
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1626
		{
			yyVAL.expr = &ast.Ellipsis{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1630
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.None}
		}
	case 257:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1634
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.True}
		}
	case 258:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1638
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.False}
		}
	case 259:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1645
		{
			yyVAL.expr = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 260:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1649
		{
			yyVAL.expr = yyDollar[2].call
		}
	case 261:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1653
		{
			slice := yyDollar[2].slice
			// If all items of a ExtSlice are just Index then return as tuple
			if extslice, ok := slice.(*ast.ExtSlice); ok {
				elts := make([]ast.Expr, len(extslice.Dims))
				for i, item := range extslice.Dims {
					if index, isIndex := item.(*ast.Index); isIndex {
						elts[i] = index.Value
					} else {
						goto notAllIndex
					}
				}
				slice = &ast.Index{SliceBase: extslice.SliceBase, Value: &ast.Tuple{ExprBase: ast.ExprBase{Pos: extslice.SliceBase.Pos}, Elts: elts, Ctx: ast.Load}}
			notAllIndex:
			}
			yyVAL.expr = &ast.Subscript{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Slice: slice, Ctx: ast.Load}
		}
	case 262:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1671
		{
			yyVAL.expr = &ast.Attribute{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Attr: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
		}
	case 263:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1677
		{
			yyVAL.slice = yyDollar[1].slice
			yyVAL.isExpr = true
		}
	case 264:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1682
		{
			if !yyDollar[1].isExpr {
				extSlice := yyVAL.slice.(*ast.ExtSlice)
				extSlice.Dims = append(extSlice.Dims, yyDollar[3].slice)
			} else {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice, yyDollar[3].slice}}
			}
			yyVAL.isExpr = false
		}
	case 265:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1694
		{
			if yyDollar[2].comma && yyDollar[1].isExpr {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice}}
			} else {
				yyVAL.slice = yyDollar[1].slice
			}
		}
	case 266:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1704
		{
			yyVAL.slice = &ast.Index{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 267:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1708
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: nil}
		}
	case 268:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1712
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: yyDollar[2].expr}
		}
	case 269:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1716
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: nil}
		}
	case 270:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1720
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: yyDollar[3].expr}
		}
	case 271:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1724
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: nil}
		}
	case 272:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1728
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: yyDollar[3].expr}
		}
	case 273:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1732
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: nil}
		}
	case 274:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1736
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: yyDollar[4].expr}
		}
	case 275:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1742
		{
			yyVAL.expr = nil
		}
	case 276:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1746
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 277:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1752
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 278:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1756
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 279:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1762
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 280:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1767
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 281:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1773
		{
			yyVAL.exprs = yyDollar[1].exprs
			yyVAL.comma = yyDollar[2].comma
		}
	case 282:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1780
		{
			elts := yyDollar[1].exprs
			if yyDollar[2].comma || len(elts) > 1 {
				yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: elts, Ctx: ast.Load}
			} else {
				yyVAL.expr = elts[0]
			}
		}
	case 283:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1791
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 284:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1798
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr, yyDollar[3].expr) // key, value order
		}
	case 285:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1803
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 286:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1809
		{
			keyValues := yyDollar[1].exprs
			d := &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Keys: nil, Values: nil}
			for i := 0; i < len(keyValues)-1; i += 2 {
				d.Keys = append(d.Keys, keyValues[i])
				d.Values = append(d.Values, keyValues[i+1])
			}
			yyVAL.expr = d
		}
	case 287:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1819
		{
			yyVAL.expr = &ast.DictComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Key: yyDollar[1].expr, Value: yyDollar[3].expr, Generators: yyDollar[4].comprehensions}
		}
	case 288:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1823
		{
			yyVAL.expr = &ast.Set{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[1].exprs}
		}
	case 289:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1827
		{
			yyVAL.expr = &ast.SetComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions}
		}
	case 290:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1833
		{
			classDef := &ast.ClassDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[5].stmts}
			yyVAL.stmt = classDef
			args := yyDollar[3].call
			if args != nil {
				classDef.Bases = args.Args
				classDef.Keywords = args.Keywords
				classDef.Starargs = args.Starargs
				classDef.Kwargs = args.Kwargs
			}
		}
	case 291:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1847
		{
			yyVAL.call = yyDollar[1].call
		}
	case 292:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1851
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 293:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1857
		{
			yyVAL.call = &ast.Call{}
		}
	case 294:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1861
		{
			yyVAL.call = yyDollar[1].call
		}
	case 295:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:1866
		{
			yyVAL.call = &ast.Call{}
		}
	case 296:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1870
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 297:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1877
		{
			yyVAL.call = yyDollar[1].call
		}
	case 298:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1881
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 299:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:1891
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			call.Kwargs = yyDollar[7].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 300:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1902
		{
			call := yyDollar[1].call
			call.Kwargs = yyDollar[3].expr
			yyVAL.call = call
		}
	case 301:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1912
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{yyDollar[1].expr}
		}
	case 302:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1917
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{
				&ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions},
			}
		}
	case 303:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1924
		{
			yyVAL.call = &ast.Call{}
			test := yyDollar[1].expr
			if name, ok := test.(*ast.Name); ok {
				yyVAL.call.Keywords = []*ast.Keyword{&ast.Keyword{Pos: name.Pos, Arg: name.Id, Value: yyDollar[3].expr}}
			} else {
				yylex.(*yyLex).SyntaxError("keyword can't be an expression")
			}
		}
	case 304:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1936
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = nil
		}
	case 305:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1941
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 306:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:1948
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
		}
	case 307:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:1957
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
				Ifs:    yyDollar[5].exprs,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
			yyVAL.comprehensions = append(yyVAL.comprehensions, yyDollar[5].comprehensions...)
		}
	case 308:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1970
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.comprehensions = nil
		}
	case 309:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1975
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].exprs...)
			yyVAL.comprehensions = yyDollar[3].comprehensions
		}
	case 310:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:1986
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 311:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:1990
		{
			yyVAL.expr = &ast.YieldFrom{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[3].expr}
		}
	case 312:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:1994
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	}
	goto yystack /* stack new state and value */
}
